
buildscript {
    repositories {
        jcenter()
        google()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.2'
    }
}

apply plugin: 'com.android.application'

repositories {
    jcenter()
    google()
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'androidx.viewpager:viewpager:1.0.0'
    implementation "androidx.fragment:fragment:1.3.5"

    implementation 'org.ocpsoft.prettytime:prettytime:4.0.5.Final'
    implementation 'org.codeberg.fynngodau:librariesDirect:3.0'
    implementation 'org.codeberg.fynngodau:chartDirect:2.0'
    implementation 'com.ogaclejapan.smarttablayout:library:2.0.0@aar'
    implementation 'org.codeberg.fynngodau:TypedRecyclerView:2.1'

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'

    def room_version = "2.3.0"
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"

}

android {
    compileSdkVersion 29

    defaultConfig {
        applicationId "godau.fynn.usagedirect"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 8
        versionName "0.7"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation":
                                      "$projectDir/schemas".toString()]
            }
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
        }
    }

    flavorDimensions "source"
    productFlavors {
        system {
            dimension "source"
            applicationIdSuffix ".system"
        }
        database {
            dimension "source"
        }
    }

    compileOptions {

        // This is for using certain useful java.time.* calls
        coreLibraryDesugaringEnabled true

        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}
