
buildscript {
    repositories {
        jcenter()
        google()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
    }
}

apply plugin: 'com.android.application'

repositories {
    jcenter()
    google()
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.viewpager:viewpager:1.0.0'
    implementation 'com.github.mfornos:humanize-slim:1.2.2'
    implementation 'org.codeberg.fynngodau:librariesDirect:fd6a5f370179b0f85b69c018a8037e1fa0ac37c2'
    implementation 'com.github.fynngodau:AndroidCharts:91964670a03dbb978a273f358b792f76a8cba493'
    implementation 'com.ogaclejapan.smarttablayout:library:2.0.0@aar'
    implementation 'org.codeberg.fynngodau:TypedRecyclerView:1.0'

    def room_version = "2.2.5"
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"

}

android {
    compileSdkVersion 28

    buildToolsVersion "28.0.3"

    defaultConfig {
        applicationId "godau.fynn.usagedirect"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 4
        versionName "0.4"
    }

    buildTypes {
        debug {
            versionNameSuffix " debug"
            applicationIdSuffix ".debug"
        }
    }

    flavorDimensions "source"
    productFlavors {
        system {
            dimension "source"
            applicationIdSuffix ".system"
        }
        database {
            dimension "source"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

}
