include 'Application'

/* Uncomment if you want to use a local copy of SmartTabLayout (requires many adjustments in library)
includeBuild('../SmartTabLayout') {
    dependencySubstitution {
        substitute module('com.ogaclejapan.smarttablayout:library') with project(':library')
    }
}
 */

/* Uncomment if you want to use a local copy of my AndroidCharts fork
includeBuild('../AndroidCharts') {
    dependencySubstitution {
        substitute module('com.github.fynngodau:AndroidCharts:alpha-1.3') with project(':AndroidCharts')
    }
}
 */