include 'Application'

/* Uncomment if you want to use a local copy of SmartTabLayout (requires many adjustments in library)
includeBuild('../SmartTabLayout') {
    dependencySubstitution {
        substitute module('com.ogaclejapan.smarttablayout:library') with project(':library')
    }
}
 */

/* Uncomment if you want to use a local chartDirect copy
includeBuild('../chartDirect') {
    dependencySubstitution {
        substitute module('org.codeberg.fynngodau:chartDirect:2.0') with project(':AndroidCharts')
    }
}
 */